name: Benchmark.Net Example
on:
  release:
    types: [published]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: preview

      - name: CD to benchmarks
        run: cd benchmarks/Pathological.Globbing.Benchmarks && dotnet run --exporters json --filter '*'

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark.Net Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: benchmarks/Pathological.Globbing.Benchmarks/BenchmarkDotNet.Artifacts/results/Pathological.Globbing.Benchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@IEvangelist'